data:
  cnhubertsoft_gate: 10
  duration: 2
  encoder: vec768l12
  encoder_hop_size: 320
  encoder_out_channels: 768
  encoder_sample_rate: 16000
  extensions:
  - wav
  filter_length: 512
  hop_length: 128
  sampling_rate: 24000
  training_files: filelists/train.txt
  unit_interpolate_mode: nearest
  validation_files: filelists/val.txt
  win_length: 512
device: cuda
env:
  comodir: logs/como
  expdir: logs/teacher
  gpu_id: 0
infer:
  method: dpm-solver++
model:
  n_chans: 512
  n_hidden: 256
  n_layers: 20
  n_spk: 9
  type: Diffusion
  use_pitch_aug: true
spk:
  TaylorSwift: 7
  TheLumineers: 3
  TheMacaronsProject: 0
  ThePaperKites: 2
  TheTallestManonEarth: 5
  TylerChilders: 8
  TylerWard: 4
  ZachBryan: 6
  ZiggyAlberts: 1
train:
  amp_dtype: fp32
  batch_size: 48
  cache_all_data: true
  cache_device: cpu
  cache_fp16: true
  comolr: 5.0e-05
  decay_step: 100000
  epochs: 100000
  gamma: 0.5
  interval_force_save: 2000
  interval_log: 10
  interval_val: 2000
  lr: 0.0001
  num_workers: 4
  save_opt: false
  weight_decay: 0
vocoder:
  ckpt: m4singer_hifigan/model_ckpt_steps_1970000.ckpt
  type: m4-gan
